name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 21]

    steps:
    # Check out the repository code
    - name: Check out code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    # Navigate to the make/nashorn directory and run tests
    - name: Run Nashorn Tests
      working-directory: make/nashorn
      run: |
        ant test
        
    # Navigate to the make/nashorn directory and run tests
    - name: Run ECMA-262 Tests
      working-directory: make/nashorn
      run: |
        ant test262-parallel
